// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package realpro

type IBuildingPermit struct {
	Period    string `json:"period"`
	Permits   int    `json:"permits"`
	Starts    int    `json:"starts"`
	Completed int    `json:"completed"`
}

type IEsi struct {
	Period      string  `json:"period"`
	CountryCode string  `json:"country_code"`
	Industry    float64 `json:"industry"`
	Services    float64 `json:"services"`
	Consumer    float64 `json:"consumer"`
	Retail      float64 `json:"retail"`
	Building    float64 `json:"building"`
	Esi         float64 `json:"esi"`
}

type IPmiMan struct {
	Dat       string  `json:"dat"`
	ManuIndex float64 `json:"manu_index"`
}

type IPmiNoman struct {
	Dat     string  `json:"dat"`
	NonManu float64 `json:"non_manu"`
}

type IPmiNonmanIndustry struct {
	Dat      string `json:"dat"`
	Industry string `json:"industry"`
	Rank     int    `json:"rank"`
	Comment  string `json:"comment"`
	Type     int    `json:"type"`
}

type IRetailSale struct {
	Period                     string `json:"period"`
	RetailSalesAndFoodServices int    `json:"retail_sales_and_food_services"`
	FoodStores                 int    `json:"food_stores"`
	NonStoreRetail             int    `json:"non_store_retail"`
	Health                     int    `json:"health"`
	ClothingHobby              int    `json:"clothing_hobby"`
	GeneralMerch               int    `json:"general_merch"`
	FoodServices               int    `json:"food_services"`
	GasStation                 int    `json:"gas_station"`
	Motors                     int    `json:"motors"`
	DomesticProducts           int    `json:"domestic_products"`
}

type IUmcsi struct {
	Period string  `json:"period"`
	Csi    float64 `json:"csi"`
}
